#   * ===== * Yang Zheng Studio * ==== * Yang Zheng Studio * ===== * 
#   *                                                              * 
#   * This file is generated by program                            * 
#   * [Movie PDB Files Generator]                                  * 
#   * in Fortran 90.                                               * 
#   * Author : Zheng Yang,                                         * 
#   *          Department of Computational Biology                 * 
#   *          University of Pittsburgh                            * 
#   * Email  : proteinyang@gmail.com                               * 
#   * Date   : 7/10/2006                                           * 
#   *                                                              * 
#   * Anisotropic Network Model (ANM) part was programmed          * 
#   * by Eran Eyal (eyal@ccbb.pitt.edu).                           * 
#   *                                                              * 
#   * For the ANM, please refer to the following paper:            * 
#   *  Atilgan, A. R., Durell, S. R., Jernigan, R. L.,             * 
#   *  Demirel, M. C., Keskin, O. & Bahar, I. (2001).              * 
#   *  Anisotropy of Fluctuation Dynamics of Proteins              * 
#   *  with an Elastic Network Model.  Biophys. J. 80, 505-515.    * 
#   *  (http://www.biophysj.org/cgi/content/abstract/80/1/505)     * 
#   *                                                              * 
#   * The output files need to be loaded in PyMOL. Please refer to * 
#   * http://pymol.sourceforge.net/                                * 
#   *                                                              * 
#   * ===== * Yang Zheng Studio * ==== * Yang Zheng Studio * ===== * 
load 3dh4_Mode_00002.pdb, 3dh4_Mode_00002
preset.pretty( "3dh4_Mode_00002")
cmd.spectrum("b",selection=("3dh4_Mode_00002"),quiet=0)
run 3dh4_Mode_00002_Arrows.py
cmd.center("all",animate=-1) 
zoom 
set cartoon_loop_radius,0.3 
set ray_opaque_background, off
